"""
student_success_index.py

Builds a Student Success Index (SSI) for predicting 9th grade academic risk
using Weight of Evidence (WOE) and Information Value (IV) methodology.

The SSI is designed to support counselors during the 8th-to-9th grade transition
by identifying students who may need additional support before or during their
first semester at Ridgemont High School.

KEY DESIGN PRINCIPLE — Controllable vs. Non-Controllable Factors:
    The scoring ALGORITHM includes both controllable factors (GPA, attendance)
    and non-controllable factors (race/ethnicity, ELL status, economic disadvantage)
    because both genuinely predict outcomes and omitting them would reduce accuracy.

    However, the student-facing REPORT shows ONLY controllable factors as
    strengths and challenges. Showing a student that their race or income level
    is a "challenge" is deflating and unhelpful — they cannot change those things.
    Counselors see the full score; students and families see actionable insights.

    This is the same principle used in medical risk models: a doctor's full risk
    calculation may include age and family history, but the patient's action plan
    focuses only on diet, exercise, and medication.

Usage:
    # Run on synthetic data (generated by generate_synthetic_data.py)
    python student_success_index.py

    # Run on your own data file
    python student_success_index.py --input your_data.csv

Output:
    woe_iv_report.csv       — WOE/IV analysis for each predictor
    student_scores.csv      — Full scored student roster
    example_reports.txt     — Sample counselor report cards
"""

import argparse
import sys
import warnings
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ── Args ──────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument("--input", default="synthetic_students.csv",
                    help="Input CSV file (default: synthetic_students.csv)")
parser.add_argument("--output-scores", default="student_scores.csv")
parser.add_argument("--output-woe", default="woe_iv_report.csv")
parser.add_argument("--output-reports", default="example_reports.txt")
args = parser.parse_args()

# ── Load data ─────────────────────────────────────────────────────────────────
print("=" * 70)
print("STUDENT SUCCESS INDEX — Shermer Middle to Ridgemont High")
print("=" * 70)

try:
    df = pd.read_csv(args.input)
except FileNotFoundError:
    print(f"\nError: {args.input} not found.")
    print("Run generate_synthetic_data.py first to create the input file.")
    sys.exit(1)

TARGET = "grade9_any_dfi"
N = len(df)
dfi_rate = df[TARGET].mean()
print(f"\nLoaded {N} students | Overall DFI rate: {dfi_rate*100:.1f}%")

# ── WOE / IV functions ────────────────────────────────────────────────────────
def bin_continuous(series, n_bins=5):
    """Bin a continuous variable into equal-frequency bins."""
    try:
        return pd.qcut(series, q=n_bins, duplicates="drop")
    except Exception:
        return pd.cut(series, bins=n_bins)

def calculate_woe_iv(df, feature_col, target_col, bins=None):
    """
    Calculate Weight of Evidence and Information Value for one feature.

    WOE = ln(Distribution of Events / Distribution of Non-Events)
    IV  = Sum of (Dist_Events - Dist_NonEvents) * WOE

    IV interpretation:
        < 0.02  : unpredictive
        0.02-0.1: weak
        0.1-0.3 : medium
        > 0.3   : strong
    """
    if bins is not None:
        df = df.copy()
        df["_bin"] = bins
        group_col = "_bin"
    else:
        group_col = feature_col

    grouped = df.groupby(group_col)[target_col].agg(["sum", "count"])
    grouped.columns = ["events", "total"]
    grouped["non_events"] = grouped["total"] - grouped["events"]

    total_events = grouped["events"].sum()
    total_non_events = grouped["non_events"].sum()

    if total_events == 0 or total_non_events == 0:
        return None, 0.0

    eps = 0.5  # Laplace smoothing to avoid log(0)
    grouped["dist_events"] = (grouped["events"] + eps) / (total_events + eps * len(grouped))
    grouped["dist_non_events"] = (grouped["non_events"] + eps) / (total_non_events + eps * len(grouped))
    grouped["woe"] = np.log(grouped["dist_events"] / grouped["dist_non_events"])
    grouped["iv_component"] = (grouped["dist_events"] - grouped["dist_non_events"]) * grouped["woe"]

    iv = grouped["iv_component"].sum()
    return grouped[["events", "non_events", "total", "woe", "iv_component"]], iv

# ── Analyze each predictor ────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("WEIGHT OF EVIDENCE ANALYSIS")
print("=" * 70)

# Controllable predictors (shown in student reports)
controllable_features = {
    "grade8_overall_gpa":   {"bins": 5, "label": "8th Grade Overall GPA"},
    "grade8_math_gpa":      {"bins": 5, "label": "8th Grade Math GPA"},
    "grade8_science_gpa":   {"bins": 5, "label": "8th Grade Science GPA"},
    "grade8_ela_gpa":       {"bins": 5, "label": "8th Grade ELA GPA"},
    "grade8_attendance_pct":{"bins": 5, "label": "8th Grade Attendance %"},
}

# Non-controllable predictors (used in algorithm only, NOT shown to students)
noncontrollable_features = {
    "race_ethnicity":           {"bins": None, "label": "Race/Ethnicity"},
    "english_learner":          {"bins": None, "label": "English Learner Status"},
    "economically_disadvantaged":{"bins": None,"label": "Economically Disadvantaged"},
    "special_education":        {"bins": None, "label": "Special Education"},
    "gender":                   {"bins": None, "label": "Gender"},
}

all_features = {**controllable_features, **noncontrollable_features}
iv_results = []
woe_maps = {}  # store WOE lookup maps for scoring

for feat, config in all_features.items():
    is_controllable = feat in controllable_features

    if config["bins"] is not None:
        bins = bin_continuous(df[feat], n_bins=config["bins"])
        woe_df, iv = calculate_woe_iv(df, feat, TARGET, bins=bins)
    else:
        woe_df, iv = calculate_woe_iv(df, feat, TARGET)

    if woe_df is None:
        continue

    # Build WOE lookup map for scoring
    if config["bins"] is not None:
        bin_edges = pd.qcut(df[feat], q=config["bins"], duplicates="drop", retbins=True)[1]
        woe_maps[feat] = {
            "type": "continuous",
            "bin_edges": bin_edges,
            "woe_values": woe_df["woe"].values,
            "labels": woe_df.index.tolist()
        }
    else:
        woe_maps[feat] = {
            "type": "categorical",
            "woe_by_category": woe_df["woe"].to_dict()
        }

    iv_results.append({
        "feature": feat,
        "label": config["label"],
        "controllable": is_controllable,
        "information_value": round(iv, 4),
        "predictive_strength": (
            "Strong" if iv > 0.3 else
            "Medium" if iv > 0.1 else
            "Weak" if iv > 0.02 else
            "Unpredictive"
        )
    })

    marker = "  [controllable]" if is_controllable else "  [non-controllable — algorithm only]"
    print(f"\n{config['label']}{marker}")
    print(f"  Information Value: {iv:.4f} ({iv_results[-1]['predictive_strength']})")
    print(woe_df[["events","non_events","total","woe"]].round(3).to_string())

iv_df = pd.DataFrame(iv_results).sort_values("information_value", ascending=False)
iv_df.to_csv(args.output_woe, index=False)
print(f"\n\nWOE/IV report saved: {args.output_woe}")

# ── Build SSI scores ──────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("SCORING — Student Success Index (0-100)")
print("=" * 70)

def get_woe_score(value, woe_map):
    """Look up the WOE score for a single student's feature value."""
    if woe_map["type"] == "continuous":
        edges = woe_map["bin_edges"]
        woe_vals = woe_map["woe_values"]
        bin_idx = np.searchsorted(edges[1:-1], value, side="right")
        bin_idx = np.clip(bin_idx, 0, len(woe_vals) - 1)
        return woe_vals[bin_idx]
    else:
        return woe_map["woe_by_category"].get(value, 0.0)

def score_student(row):
    """Calculate raw WOE score for one student using all features."""
    raw = 0.0
    for feat, woe_map in woe_maps.items():
        iv = iv_df.loc[iv_df["feature"] == feat, "information_value"]
        weight = float(iv.values[0]) if len(iv) > 0 else 0.0
        woe = get_woe_score(row[feat], woe_map)
        raw += woe * weight
    return raw

print("\nCalculating SSI scores...")
df["raw_score"] = df.apply(score_student, axis=1)

# Normalize to 0-100 (higher = better prepared, lower = higher risk)
raw_min, raw_max = df["raw_score"].min(), df["raw_score"].max()
df["ssi_score"] = (1 - (df["raw_score"] - raw_min) / (raw_max - raw_min)) * 100
df["ssi_score"] = df["ssi_score"].round(1)

# Risk categories
def assign_risk(score):
    if score >= 65:
        return "On Track"
    elif score >= 40:
        return "Monitor"
    else:
        return "High Risk"

df["risk_category"] = df["ssi_score"].apply(assign_risk)

# Validation
print("\nVALIDATION — Does the SSI predict actual DFI outcomes?")
print("-" * 50)
for category in ["High Risk", "Monitor", "On Track"]:
    group = df[df["risk_category"] == category]
    if len(group) > 0:
        actual_dfi = group[TARGET].mean() * 100
        print(f"  {category:12s}: {len(group):3d} students | {actual_dfi:.0f}% actual DFI rate")

# ── Generate counselor report cards ──────────────────────────────────────────
print("\n" + "=" * 70)
print("EXAMPLE COUNSELOR REPORT CARDS")
print("=" * 70)

CONTROLLABLE_LABELS = {
    "grade8_overall_gpa":    "Overall GPA",
    "grade8_math_gpa":       "Math GPA",
    "grade8_science_gpa":    "Science GPA",
    "grade8_ela_gpa":        "ELA GPA",
    "grade8_attendance_pct": "Attendance %",
}

def get_controllable_signals(row):
    """
    Return ranked strengths and challenges from controllable factors only.
    Higher WOE = strength; lower WOE = challenge.
    """
    signals = []
    for feat, label in CONTROLLABLE_LABELS.items():
        woe = get_woe_score(row[feat], woe_maps[feat])
        signals.append((label, woe, row[feat]))
    signals.sort(key=lambda x: x[1], reverse=True)
    strengths = [(l, v) for l, _, v in signals[:3] if _ > 0]
    challenges = [(l, v) for l, _, v in reversed(signals) if _ < 0][:3]
    return strengths, challenges

def generate_report(row):
    strengths, challenges = get_controllable_signals(row)

    if row["risk_category"] == "High Risk":
        message = (f"PRIORITY SUPPORT: Connect with {row['first_name']} before school starts. "
                   f"Consider Summer Bridge and check in during first 6 weeks.")
    elif row["risk_category"] == "Monitor":
        message = (f"WATCH: Schedule a check-in with {row['first_name']} during the first "
                   f"6 weeks. Targeted support in challenge areas recommended.")
    else:
        message = (f"ON TRACK: {row['first_name']} is well-prepared for 9th grade. "
                   f"Continue supporting identified strengths.")

    lines = [
        "=" * 55,
        f"STUDENT SUCCESS INDEX — Counselor Report",
        f"Sending School: Shermer Middle School",
        f"Receiving School: Ridgemont High School",
        "=" * 55,
        f"Student:    {row['first_name']} {row['last_name']}  (ID: {row['student_id']})",
        f"SSI Score:  {row['ssi_score']:.1f} / 100",
        f"Category:   {row['risk_category']}",
        "",
        "STRENGTHS (controllable factors):",
    ]
    for label, val in strengths:
        lines.append(f"  + {label}: {val}")
    if not strengths:
        lines.append("  (No notable strengths identified in controllable factors)")

    lines.append("")
    lines.append("CHALLENGES (controllable factors):")
    for label, val in challenges:
        lines.append(f"  - {label}: {val}")
    if not challenges:
        lines.append("  (No notable challenges identified in controllable factors)")

    lines += ["", "COUNSELOR ACTION:", f"  {message}", ""]
    return "\n".join(lines)

# Sample one from each risk category
report_lines = [
    "SAMPLE COUNSELOR REPORT CARDS",
    "Generated by Student Success Index",
    "All students are synthetic/fictional",
    "",
]

for category in ["High Risk", "Monitor", "On Track"]:
    sample = df[df["risk_category"] == category]
    if len(sample) > 0:
        row = sample.iloc[0]
        report_lines.append(generate_report(row))

with open(args.output_reports, "w") as f:
    f.write("\n".join(report_lines))

# Save full scored roster
output_cols = [
    "student_id", "last_name", "first_name",
    "grade8_overall_gpa", "grade8_math_gpa", "grade8_science_gpa",
    "grade8_ela_gpa", "grade8_attendance_pct",
    "ssi_score", "risk_category", "grade9_any_dfi"
]
df[output_cols].sort_values("ssi_score").to_csv(args.output_scores, index=False)

print(f"\nOutputs saved:")
print(f"  {args.output_woe}     — WOE/IV analysis")
print(f"  {args.output_scores}      — Scored student roster")
print(f"  {args.output_reports}   — Example counselor reports")
print(f"\nRisk category breakdown:")
print(df["risk_category"].value_counts().to_string())
